### PR TITLE
Support python 3.10

### PR DESCRIPTION
**Pull request by roxanebellot**
In this PR i propose to support python 3.10 from django 3.2.

I quickly tested locally and everything looked fine

### CODE REVIEW

**Comment by artofhuman** [comment]
@roxanebellot Thanks for your PR. But it looks like tests actions are stale and tests are failed. If you can check this, it would be nice.

**Comment by roxanebellot** [comment]
Yes of course :+1:

**Comment by artofhuman** [comment]
Test are failed for django20, I think we can exclude support for 2.0.

**Comment by roxanebellot** [comment]
Would you have insights on why a django 2.0 pipeline fails with an error linked to a django 3 change (`TypeError: __init__() got an unexpected keyword argument 'ignore_conflicts'`) ?

**Comment by artofhuman** [comment]
I suppose API had been changed.

**Pull request merged**
